# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - run: yarn
    - run: yarn test
  
  publish_docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: rlespinasse/github-slug-action@master
      - name: Print slug variables
        run: |
          echo ${{ env.GITHUB_REF_SLUG }}
          echo ${{ env.GITHUB_HEAD_REF_SLUG }}
          echo ${{ env.GITHUB_BASE_REF_SLUG }}
      - uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: antoiner/books-frontend
          tags: ${{ env.GITHUB_HEAD_REF_SLUG }}

  deploy:
    needs: publish_docker
    steps:
      - name: Comment deploy branch url
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'A preview of this branch will be deployed here http://books.${{ env.GITHUB_HEAD_REF_SLUG }}.areyt.net'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event.pull_request.opened
      - name: Comment delete k8s things
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Delete ${{ env.GITHUB_HEAD_REF_SLUG }} k8s things'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event.pull_request.merged
