# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - run: yarn
    - run: yarn test
  
  publish_docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: rlespinasse/github-slug-action@1.1.1
      - uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: antoiner/books-frontend
          tags: ${{ env.GITHUB_HEAD_REF_SLUG }}

  deploy:
    needs: publish_docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rlespinasse/github-slug-action@1.1.1

      - name: Upgrade Helm
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: helm upgrade books-frontend ./books-frontend -n ${{ env.GITHUB_HEAD_REF_SLUG }}

      - name: Restart rollout
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: kubectl rollout restart deploy/books-frontend -n ${{ env.GITHUB_HEAD_REF_SLUG }}
