name: Create Review App Resources

on:
  pull_request:
    types: [opened]

jobs:
  delete-review-app:
    runs-on: ubuntu-latest
    name: Create Review App
    steps:
    - uses: actions/checkout@v2
    - uses: rlespinasse/github-slug-action@master
    - name: Comment
      uses: thollander/actions-comment-pull-request@master
      with:
        message: 'Deploying preview on ${{ env.GITHUB_HEAD_REF_SLUG }}.books.areyt.net'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create k8s namespace
      uses: wahyd4/kubectl-helm-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: kubectl create namespace ${{ env.GITHUB_HEAD_REF_SLUG }}

    - name: Install helm package
      uses: wahyd4/kubectl-helm-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: helm install books-frontend -n ${{ env.GITHUB_HEAD_REF_SLUG }} --set Gitsha=${{ GITHUB_SHA }} ./books-frontend
